application: savvadia
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:                                                                      
- name: jinja2                                                                  
  version: latest 
- name: django
  version: latest
- name: markupsafe                                                              
  version: latest 

handlers:
- url: /(.*css)
  static_files: stylesheets/\1
  upload: stylesheets/(.*)
- url: /imgs/(.*)
  static_files: imgs/\1
  upload: imgs/(.*)
- url: /.*  
  script: main.py


